### ISSUE TITLE
File that may not exist

### ISSUE THREAD

**Issue by veotani** [itesoro/creepy#45]
File `~/.ssh/authorized_keys` may not exist sometimes when we [open it](https://github.com/itesoro/creepy/blob/master/creepy/protocol/handshake.py#L44). For example in test environment it can be absent. It is necessary to check if it exist before opening it (`os.exists`). If it doesn't exist, don't open it.

**Comment by progbeat** [comment]
It's better to catch exceptions raised by `open()`. Checking if file exists doesn't work in general case:
- File may exist, but there's no access.
- File can be deleted just after `os.exist` check, in such case exception still will be raised.
